### ISSUE TITLE
Unicode breaks into new line ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by timche** [leebyron/bigtype#1]
Normally `¯\_(ツ)_/¯` should fit in one line, instead the last character `¯` breaks into a new line.

See http://bigty.pe/%C2%AF%5C_(%E3%83%84)_%2F%C2%AF

![untitled](https://cloud.githubusercontent.com/assets/8075074/20398514/08baef1a-acee-11e6-9bf6-c8e5589a4818.gif)

Using Chrome Version 54.0.2840.98 (64-bit) on macOS.

**Comment by leebyron** [comment]
I think chrome's text renderer assumes that `/` is a valid character to wrap at (similar to `-`).

There's probably some CSS magic that turns this behavior off and only breaks on whitespace?

**Comment by leebyron** [comment]
It doesn't look good. http://unicode.org/reports/tr14/ is what most browsers proport to implement, and there's no great way to override this other than wrapping chunks of text in `span`s which can make the editor a lot more complicated.

**Comment by leebyron** [comment]
I just made the editor more complicated. It's all worth it to make [¯\_(ツ)_/¯](http://bigty.pe/%C2%AF%5C_%28%E3%83%84%29_%2F%C2%AF) work right!

**Comment by timche** [comment]
Wow, awesome! Thanks! 🤗
